server {
    listen 80;
    server_name localhost;
    
    # Habilitando compressão GZIP para otimização PWA e Load
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Cabeçalhos de Segurança Padrão
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    root /usr/share/nginx/html;
    index index.html;

    # Qualquer rota do React deve devolver o index.html (SPA Fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache agresivo para assets imutáveis e Service Worker PWA
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webmanifest)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
